### ISSUE TITLE
Resolving objectstatus of datapower takes way more than 1s

### ISSUE THREAD

**Issue by djarcan** [IBM/apiconnect-trawler#59]
Hello,

in our deployment, the trawler times out while fetching the objectstatus over the RMI of the datapower gateways.
Currently, the timout is hardcoded to 1s.

In our test environment, we observe times of 5s (environment A) and 15s (environment B) with a rough download size of 25MiB.

Please provide a way to configure such timeouts from the outside by e.g. using environment variables which we can configure in a configmap.

Affected line:
https://github.com/IBM/apiconnect-trawler/blob/main/datapower_net.py#L264

**Comment by djarcan** [comment]
Note: the affected line is only an example, we already observed other datapower metrics to take longer than 1s to fetch for.
At best, all datapower relevant timeouts can be configured. (Otherwise, there will be more issues to open)

**Comment by rickymoorhouse** [comment]
Yes in bigger environments it's quite optimistic to get this all back in 1s - configurable DP timeouts would definitely be the way to go
